Repository operate-first/continuous-deployment, pull requests merged in 2020-10, with the labels that each got.

#39 Fixes to the Quicklab install of ArgoCD.
  docs/downstream/quicklab.md
Labels: size/S

#44 Fixes to the ODH install on CRC howto
  docs/downstream/crc.md
  docs/downstream/odh-install-crc.md
  examples/odh-deployment-app.yaml
  examples/odh-operator-app.yaml
Labels: size/XS

#46 Update image revision
  manifests/base/deployments/argocd-repo-server_patch.yaml
Labels: size/XS

#49 Add PVs to Quicklab cluster via NFS
  docs/downstream/on-cluster-persistent-storage/README.md
  docs/downstream/on-cluster-persistent-storage/env.yaml
  docs/downstream/on-cluster-persistent-storage/playbook.yaml
Labels: size/L

#50 Add index of howtos and quicklab steps for ODH.
  README.md
  docs/downstream/odh-install-quicklab.md
  docs/index.md
  examples/odh-deployment-app.yaml
  examples/odh-operator-app.yaml
Labels: size/M

#51 Add instructions on increasing CRC disk size.
  docs/downstream/crc-disk-size.md
  docs/downstream/crc.md
Labels: size/M

#53 Multiple gpg
  OWNERS
  manifests/base/deployments/argocd-repo-server_patch.yaml
  manifests/base/services/argocd_metrics_service_patch.yaml
  manifests/base/services/argocd_server_metrics_service_patch.yaml
Labels: size/S

#54 moved published doc to independent sub-directory
  docs/downstream/crc-disk-size.md
  docs/index.md
  docs/publish/versions.md
Labels: size/XS

#55 Update quicklab documentation
  docs/downstream/odh-install-quicklab.md
  docs/downstream/quicklab.md
Labels: approved, size/S

#58 Include setting up of PVs in quicklab documentation
  docs/downstream/odh-install-quicklab.md
Labels: approved, size/S

#52 Add info on ODH deployment modification.
  docs/assets/images/argocd-app-edit-repo.png
  docs/index.md
  docs/modify-odh-deployment.md
Labels: approved, size/M

#59 Fix a typo in index.md
  docs/index.md
Labels: approved, size/XS

#56 Update ODH apps to reflect odh repo changes
  docs/downstream/odh-install-crc.md
  examples/odh-deployment-app.yaml
Labels: approved, size/M

#61 Add gpg step to quicklab instructions
  docs/downstream/quicklab.md
Labels: approved, documentation, size/XS

#63 Update image revision to 1.7.4-3
  manifests/base/deployments/argocd-repo-server_patch.yaml
Labels: approved, size/XS

#62 Update index.md
  docs/index.md
Labels: approved, documentation, size/S
