Repository operate-first/continuous-deployment, pull requests merged in 2020-12, with the labels that each got.

#47 Add a scripts to ArgoCD and ODH.
  deploy-argocd-crc.sh
  deploy-argocd-quicklab.sh
  deploy-odh-crc.sh
  deploy-odh-quicklab.sh
Labels: approved, hacktoberfest-accepted, size/L

#75 fix: after eager sesheta merge
  deploy-odh-crc.sh
Labels: approved, size/XS

#77 Add instructions for using multiple keys with ArgoCD
  docs/manage_your_app_secrets.md
Labels: approved, size/S

#78 minor changes in documentation
  README.md
  docs/give_argocd_access_to_your_project.md
Labels: approved, size/S

#81 Update CRC setup instructions
  docs/downstream/crc.md
Labels: approved, size/S
