Repository operate-first/continuous-deployment, pull requests merged in 2021-03, with the labels that each got.

#120 chore: Use .prow.yaml instead of .aicoe-ci.yaml
  .aicoe-ci.yaml
  .prow.yaml
Labels: approved, lgtm, size/M

#121 Split app of apps into one for zero and infra each.
  manifests/overlays/moc-infra/applications/app-of-apps-infra.yaml
  manifests/overlays/moc-infra/applications/app-of-apps-zero.yaml
  manifests/overlays/moc-infra/applications/kustomization.yaml
Labels: approved, lgtm, size/S

#122 Update AOA names to be unique
  manifests/overlays/moc-infra/applications/app-of-apps-infra.yaml
  manifests/overlays/moc-infra/applications/app-of-apps-zero.yaml
Labels: approved, lgtm, size/XS

#125 Turn off autosync for AoA.
  manifests/overlays/moc-infra/applications/app-of-apps-infra.yaml
  manifests/overlays/moc-infra/applications/app-of-apps-zero.yaml
Labels: approved, lgtm, size/S

#124 Update projects to point to zero cluster.
  manifests/overlays/moc-infra/projects/data-science.yaml
  manifests/overlays/moc-infra/projects/mesh-for-data.yaml
  manifests/overlays/moc-infra/projects/operate-first.yaml
  manifests/overlays/moc-infra/projects/rekor.yaml
  manifests/overlays/moc-infra/projects/thoth.yaml
  manifests/overlays/moc-infra/projects/workshops.yaml
Labels: do-not-merge/hold, lgtm, size/S

#128 Add observatorium-operator namespace to operate-first project
  manifests/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, lgtm, size/XS

#129 Add routes for argocd metrics
  manifests/base/routes/argocd_server_route.yaml
Labels: approved, lgtm, size/M

#130 Add openshift-operators to op1st proj
  manifests/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, size/XS

#132 feat: Relocate ODH operator
  manifests/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, size/XS

#133 chore: Remove naved001 from OWNERS
  OWNERS
Labels: size/XS

#134 allow operate-first group to deploy to tekton-pipelines namespaces
  manifests/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, size/XS

#135 Onboard curator cluster
  manifests/overlays/moc-infra/applications/app-of-apps-curator.yaml
  manifests/overlays/moc-infra/applications/kustomization.yaml
Labels: approved, lgtm, size/S

#136 Point curator AoA to infra.
  manifests/overlays/moc-infra/applications/app-of-apps-curator.yaml
Labels: approved, size/XS

#137 Reference app-of-apps from argocd-apps repo.
  manifests/overlays/moc-infra/applications/app-of-apps-curator.yaml
  manifests/overlays/moc-infra/applications/app-of-apps-infra.yaml
  manifests/overlays/moc-infra/applications/app-of-apps-zero.yaml
  manifests/overlays/moc-infra/applications/kustomization.yaml
Labels: approved, do-not-merge/hold, lgtm, size/M

#138 add b4mad
  manifests/overlays/moc-infra/configs/argo_cm/dex.config
  manifests/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  manifests/overlays/moc-infra/projects/b4mad.yaml
  manifests/overlays/moc-infra/projects/kustomization.yaml
Labels: approved, lgtm, size/M

#139 feat: Introduce Lab CI/CD ArgoCD project
  manifests/overlays/moc-infra/configs/argo_cm/dex.config
  manifests/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  manifests/overlays/moc-infra/projects/kustomization.yaml
  manifests/overlays/moc-infra/projects/lab-cicd.yaml
Labels: approved, lgtm, size/M

#140 chore(prow): Lower CPU request
  .prow.yaml
Labels: approved, size/XS
