Repository operate-first/continuous-deployment, pull requests merged in 2021-02, with the labels that each got.

#102 Update owners file.
  OWNERS
Labels: approved, size/S

#101 Add a global project template
  manifests/overlays/moc-cnv/configs/argo_cm/globalProjects
  manifests/overlays/moc-cnv/kustomization.yaml
  manifests/overlays/moc-cnv/projects/data-science.yaml
  manifests/overlays/moc-cnv/projects/global_project.yaml
  manifests/overlays/moc-cnv/projects/kustomization.yaml
  manifests/overlays/moc-cnv/projects/mesh-for-data.yaml
  manifests/overlays/moc-cnv/projects/operate-first.yaml
  manifests/overlays/moc-cnv/projects/rekor.yaml
  manifests/overlays/moc-cnv/projects/thoth.yaml
Labels: approved, size/XXL

#105 Add kfdef perms to opfirst project
  manifests/overlays/moc-cnv/projects/operate-first.yaml
Labels: approved, size/XS

#104 feat: Create workshops app project
  manifests/overlays/moc-cnv/configs/argo_cm/dex.config
  manifests/overlays/moc-cnv/configs/argo_rbac_cm/policy.csv
  manifests/overlays/moc-cnv/projects/kustomization.yaml
  manifests/overlays/moc-cnv/projects/workshops.yaml
Labels: approved, lgtm, size/M

#106 feat: Enable data science project to deploy to ODH Argo namespace
  manifests/overlays/moc-cnv/projects/data-science.yaml
Labels: approved, lgtm, size/XS

#107 Fix spelling
  docs/setup_argocd_dev_environment.md
Labels: approved, lgtm, size/XS

#109 Update destination clusters to infra/cnv accordingly.
  manifests/overlays/moc-base/projects/data-science.yaml
  manifests/overlays/moc-base/projects/mesh-for-data.yaml
  manifests/overlays/moc-base/projects/operate-first.yaml
  manifests/overlays/moc-base/projects/rekor.yaml
  manifests/overlays/moc-base/projects/thoth.yaml
  manifests/overlays/moc-base/projects/workshops.yaml
Labels: approved, size/S

#111 Add ml prague workshop cluster
  manifests/overlays/moc-base/projects/workshops.yaml
  manifests/overlays/moc-base/secrets/clusters/ml-prague-ws.enc.yaml
  manifests/overlays/moc-base/secrets/clusters/secret-generator.yaml
Labels: approved, size/M

#112 Add a note on using the CLI.
  docs/setup_argocd_dev_environment.md
Labels: approved, lgtm, size/S

#118 Fix example apps to match repository structure.
  deploy-odh-crc.sh
  deploy-odh-quicklab.sh
  examples/odh-deployment-app.yaml
  examples/odh-operator-app.yaml
Labels: approved, size/S

#115 Exclude the tekton based resources from argocd
  manifests/overlays/moc-infra/configs/argo_cm/resource.exclusions
  manifests/overlays/moc-infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#117 fix: Enable read access without authentication
  manifests/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  manifests/overlays/moc-infra/configs/argo_rbac_cm/policy.default
  manifests/overlays/moc-infra/kustomization.yaml
  manifests/overlays/moc-infra/projects/workshops.yaml
Labels: approved, do-not-merge/needs-rebase, lgtm, size/S

#119 Enable auto sync for app of apps.
  manifests/overlays/moc-infra/applications/app-of-apps.yaml
Labels: approved, lgtm, size/XS
