Repository operate-first/continuous-deployment, pull requests merged in 2021-01, with the labels that each got.

#85 Update ArgoCD to 1.8.1
  .aicoe-ci.yaml
  Dockerfile
  docs/admin/update_argocd.md
  docs/downstream/crc.md
  docs/publish/versions.md
  manifests/base/deployments/argocd-application-controller_patch.yaml
  manifests/base/deployments/argocd-dex-server_patch.yaml
  manifests/base/deployments/argocd-redis_patch.yaml
  manifests/base/deployments/argocd-repo-server_patch.yaml
  manifests/base/deployments/argocd-server_patch.yaml
  manifests/base/imagestreams/argocd-custom.yaml
  manifests/base/imagestreams/argocd-dex-server.yaml
  manifests/base/imagestreams/redis.yaml
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
Labels: approved, size/L

#86 Update dev cluster to use in-cluster name & use all namespaces in the spec
  docs/admin/add_namespace_to_cluster.md
  docs/downstream/odh-install-crc.md
  examples/odh-deployment-app.yaml
  examples/odh-operator-app.yaml
  manifests/overlays/dev/applications/dev_app/dev-app.yaml
  manifests/overlays/dev/secrets/clusters/dev.cluster.example.enc.yaml
Labels: approved, size/S

#89 Add moc-cnv artifacts for new management cluster
  manifests/overlays/moc-cnv/applications/kustomization.yaml
  manifests/overlays/moc-cnv/configs/argo_cm/configManagementPlugins
  manifests/overlays/moc-cnv/configs/argo_cm/dex.config
  manifests/overlays/moc-cnv/configs/argo_cm/envs
  manifests/overlays/moc-cnv/configs/argo_rbac_cm/policy.csv
  manifests/overlays/moc-cnv/kustomization.yaml
  manifests/overlays/moc-cnv/projects/cluster-management.yaml
  manifests/overlays/moc-cnv/projects/data-science.yaml
  manifests/overlays/moc-cnv/projects/kustomization.yaml
  manifests/overlays/moc-cnv/projects/operate-first.yaml
  manifests/overlays/moc-cnv/projects/rekor.yaml
  manifests/overlays/moc-cnv/projects/thoth.yaml
  manifests/overlays/moc-cnv/secrets/.sops.yaml
  manifests/overlays/moc-cnv/secrets/auth/argocd-secret.yaml
  manifests/overlays/moc-cnv/secrets/auth/dex-server-sa.yaml
  manifests/overlays/moc-cnv/secrets/gpg/secret-generator.yaml
  manifests/overlays/moc-cnv/secrets/gpg/secret.enc.yaml
  manifests/overlays/moc-cnv/serviceaccounts/argocd-dex-server.yaml
Labels: approved, size/XXL

#92 Move dev sops yaml to dev folder
  manifests/overlays/dev/.sops.yaml
Labels: approved, size/XS

#94 Add mesh-for-data argocd project
  manifests/overlays/moc-cnv/configs/argo_cm/dex.config
  manifests/overlays/moc-cnv/projects/kustomization.yaml
  manifests/overlays/moc-cnv/projects/mesh-for-data.yaml
Labels: approved, onboarding, size/L

#96 Update ArgoCD to 1.8.3, helm-secrets, ksops
  Dockerfile
  docs/admin/update_argocd.md
  docs/publish/versions.md
  manifests/base/kustomization.yaml
  manifests/crds/kustomization.yaml
  manifests/overlays/moc-cnv/kustomization.yaml
Labels: approved, size/S

#97 feat: Allow ArgoCD in operate-first project to deploy to openshift-logging
  manifests/overlays/moc-cnv/projects/operate-first.yaml
Labels: approved, size/XS

#98 Add clusterlogging to op1st perms
  manifests/overlays/moc-cnv/projects/operate-first.yaml
Labels: approved, size/XS
